### ISSUE TITLE
Fhir Source example is using 2 properties not part of the catalog

### ISSUE THREAD

**Issue by apupier** [apache/camel-kafka-connector-examples#292]
* https://camel.apache.org/components/latest/dataformats/fhirJson-dataformat.html

https://github.com/apache/camel-kafka-connector-examples/blob/198d73de6ea9ad5f51bf6f20597a8d012fc9fe1f/fhir/source/CamelFhirSourceConnector.properties#L27

Not found somethign related, should be removed from example? or it is missing from the catalog?

* https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-fhir-kafka-source-connector.html

https://github.com/apache/camel-kafka-connector-examples/blob/198d73de6ea9ad5f51bf6f20597a8d012fc9fe1f/fhir/source/CamelFhirSourceConnector.properties#L36

Should it be `camel.source.endpoint.serverUrl`?

**Comment by oscerd** [comment]
camel.source.marshal is a dataformat specification, so it's not part of the catalog ootb.

The other yes, it should be camel.source.endpoint.serverUrl

@luigidemasi is that a leftover? Thanks

**Comment by apupier** [comment]
updated my first comment, I pointed to the wrong lien for the first reported issue. it is `camel.dataformat.fhirJson.enabled` which is missing, not `camel.source.marshal` as i wrongly reported

**Comment by oscerd** [comment]
That's a specific property of the dataformat, so, no, it's not part of the catalog. It's like setting a field value on a POJO.

**Comment by apupier** [comment]
> That's a specific property of the dataformat, so, no, it's not part of the catalog. It's like setting a field value on a POJO.

ok, then it is a bug in org.apache.camel.catalog.CamelCatalog.validateConfigurationProperty(String) method which is reporting a false positive

**Comment by oscerd** [comment]
It's not part of the ckc catalog.

**Comment by luigidemasi** [comment]
> camel.source.marshal is a dataformat specification, so it's not part of the catalog ootb.
> 
> The other yes, it should be camel.source.endpoint.serverUrl
> 
> @luigidemasi is that a leftover? Thanks

No, it's not. It's the first parameter of the [searchByUrl](https://camel.apache.org/components/latest/fhir-component.html#_api_search) method.

```java-properties
camel.source.endpoint.serverUrl=http://hapi.fhir.org/baseR4
camel.source.endpoint.url=/Patient
```

**Comment by apupier** [comment]
> > camel.source.marshal is a dataformat specification, so it's not part of the catalog ootb.
> > The other yes, it should be camel.source.endpoint.serverUrl
> > @luigidemasi is that a leftover? Thanks
> 
> No, it's not. It's the first parameter of the [searchByUrl](https://camel.apache.org/components/latest/fhir-component.html#_api_search) method.
> 
> ```java-properties
> camel.source.endpoint.serverUrl=http://hapi.fhir.org/baseR4
> camel.source.endpoint.url=/Patient
> ```

ok sounds like the Camel Catalog is reporting false positive for API based components in Properties files then

**Comment by apupier** [comment]
> > That's a specific property of the dataformat, so, no, it's not part of the catalog. It's like setting a field value on a POJO.
> 
> ok, then it is a bug in org.apache.camel.catalog.CamelCatalog.validateConfigurationProperty(String) method which is reporting a false positive

reported https://issues.apache.org/jira/browse/CAMEL-16248
