### ISSUE TITLE
Docker examples contains 3 parameters not part of the catalog

### ISSUE THREAD

**Issue by apupier** [apache/camel-kafka-connector-examples#293]
* https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-docker-kafka-source-connector.html

  https://github.com/apache/camel-kafka-connector-examples/blob/198d73de6ea9ad5f51bf6f20597a8d012fc9fe1f/docker/docker-source-stats/config/CamelDockerSourceConnector.properties#L30

  not found another one which seems related

* https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-docker-kafka-sink-connector.html

  https://github.com/apache/camel-kafka-connector-examples/blob/198d73de6ea9ad5f51bf6f20597a8d012fc9fe1f/docker/docker-sink-pull/config/CamelDockerSinkConnector.properties#L31

  not found another one which seems related

* https://camel.apache.org/camel-kafka-connector/latest/connectors/camel-docker-kafka-sink-connector.html

  https://github.com/apache/camel-kafka-connector-examples/blob/198d73de6ea9ad5f51bf6f20597a8d012fc9fe1f/docker/docker-sink-tag/config/CamelDockerSinkConnector.properties#L32

  not found another one which seems related

**Comment by oscerd** [comment]
These are headers. In camel-docker there is a mapping between particular header and endpoint options, so they cannot be part of the catalog. They are not part of the camel-catalog too

**Comment by apupier** [comment]
then the Catalog validate method is returnign false positives but I guess that it is nto specific to Camel kafka connector and should be reported in core Camel

**Comment by apupier** [comment]
> then the Catalog validate method is returnign false positives but I guess that it is nto specific to Camel kafka connector and should be reported in core Camel

reported https://issues.apache.org/jira/browse/CAMEL-16249
