### ISSUE TITLE
Review Infinispan examples after component splitting

### ISSUE THREAD

**Issue by oscerd** [apache/camel-kafka-connector-examples#300]
From: https://github.com/apache/camel-kafka-connector/issues/1068

**Comment by oscerd** [comment]
@apupier this should be ok now.

**Comment by apupier** [comment]
I confirm that it is fine now.
played locally succesfully com.github.cameltooling.lsp.internal.diagnostic.CamelKafkaConnectorOfficialExamplesDiagnosticTest.testSpecificGitRepoExamples() modified to point to master and removed exclusion of Infinispan example.
