### ISSUE TITLE
Create camel-kafka-connector-examples-0.9.0 tag

### ISSUE THREAD

**Issue by apupier** [apache/camel-kafka-connector-examples#314]
tag has been created on camel-kafka-connector repository, need tobe created in the example one: https://github.com/apache/camel-kafka-connector/releases/tag/camel-kafka-connector-0.9.0

**Comment by oscerd** [comment]
https://github.com/apache/camel-kafka-connector-examples/releases/tag/camel-kafka-connector-examples-0.9.0
