### ISSUE TITLE
camel-tar.gzfile Not Found

### ISSUE THREAD

**Issue by danrlyon** [apache/camel-kafka-connector-examples#316]
In the example, [aws2s3 Readme.adoc](https://github.com/apache/camel-kafka-connector-examples/blob/master/aws2-s3/aws2-s3-sink-with-zip-aggregation/README.adoc), the `camel-zipfile` artifact was updated to 

```
...
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-tar.gzfile</artifactId>
      <version>3.4.2</version>
    </dependency>
...
```
Was this a mistake? This may have been an error when replacing `.zip` target with `.tar.gz`. It appears to work with ckc version 0.9.0 and
```
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-zipfile</artifactId>
      <version>3.5.0</version>
    </dependency>
```

**Comment by oscerd** [comment]
Thanks. Fixed.
