### ISSUE TITLE
camel-kafka-connector-examples

### ISSUE THREAD

**Issue by fywf555** [apache/camel-kafka-connector-examples#330]
## Open the SQL configuration file at $EXAMPLES/sql/sql-source/config/CamelSqlSourceConnector.properties

name=CamelSqlSourceConnector
connector.class=org.apache.camel.kafkaconnector.sql.CamelSqlSourceConnector
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

topics=mytopic

camel.component.sql.dataSource.user=postgres
camel.component.sql.dataSource.password=mysecretpassword
camel.component.sql.dataSource.serverName=172.17.0.2
camel.component.sql.dataSource=#class:org.postgresql.ds.PGSimpleDataSource

camel.source.path.query=select * from accounts

## Please tell me how to select database
i try to use 
```
camel.component.sql.dataSource.serverName=172.17.0.2:5432/test
```
but faild

**Comment by oscerd** [comment]
You need to point to the address of an existing database. The address there is just an example

**Comment by taobingqing** [comment]
I can't find it either

**Comment by oscerd** [comment]
Read the Readme https://github.com/apache/camel-kafka-connector-examples/tree/main/sql/sql-source#setup-the-docker-image

**Comment by oscerd** [comment]
We write the Readme for this purpose

**Comment by fywf555** [comment]
it is worked and use the default database;
![image](https://user-images.githubusercontent.com/26627032/157612069-028a2621-0f57-497c-bf96-2e27442d56f4.png)

```
name=CamelSqlSourceConnector
connector.class=org.apache.camel.kafkaconnector.sql.CamelSqlSourceConnector
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

topics=mytopic

camel.component.sql.dataSource.user=postgres
camel.component.sql.dataSource.password=ab.123456
camel.component.sql.dataSource.serverName=10.14.16.4:5432
camel.component.sql.dataSource=#class:org.postgresql.ds.PGSimpleDataSource
camel.source.path.query=select * from account
```
![image](https://user-images.githubusercontent.com/26627032/157612680-b8edcc8d-ff94-4941-96eb-314f2c4383a4.png)


but i want to use another database,i try 
```
name=CamelSqlSourceConnector
connector.class=org.apache.camel.kafkaconnector.sql.CamelSqlSourceConnector
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

topics=mytopic

camel.component.sql.dataSource.user=postgres
camel.component.sql.dataSource.password=ab.123456
camel.component.sql.dataSource.serverName=10.14.16.4:5432/test
camel.component.sql.dataSource=#class:org.postgresql.ds.PGSimpleDataSource
camel.source.path.query=select * from invoice
```
and failed
![image](https://user-images.githubusercontent.com/26627032/157612614-893506f6-dbfc-48ea-9753-608667431352.png)

**Comment by oscerd** [comment]
Change the database nane according to the name you need to point. The error is clear

**Comment by fywf555** [comment]
i understand....it a silly question

**Comment by oscerd** [comment]
No, it's not a silly question. We need to explain it better in the example. Let me improve the README.

**Comment by oscerd** [comment]
The commit should explain a bit better how to do it. Thanks for asking. We're always trying to improve the documentation.
